name: Build ARM64 with CMake, liquid-dsp, and SoapySDR

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-arm64:
    name: Native ARM64 Build
    runs-on: ubuntu-22.04-arm64

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git cmake g++ libpython3-dev python3-numpy swig \
            binutils-dev libdw-dev gfortran hackrf libhackrf-dev libfftw3-dev \
            ninja-build libiio-dev libiio-utils libasound-dev \
            libboost-all-dev python3 python3-yaml \
            libglfw3-dev vim libxkbcommon-dev libusb-1.0-0-dev libxml2-dev \
            flex bison libavahi-client-dev libaio-dev libcurl4-openssl-dev \
            automake autoconf

      # 3. Build and install liquid-dsp v1.6.0
      - name: Build and Install liquid-dsp
        run: |
          git clone https://github.com/jgaeddert/liquid-dsp
          cd liquid-dsp
          git checkout v1.6.0
          ./bootstrap.sh
          ./configure
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      # 4. Build and install SoapySDR (master)
      - name: Build and Install SoapySDR
        run: |
          git clone https://github.com/pothosware/SoapySDR.git
          cd SoapySDR
          git pull origin master
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      # 5. Configure sdrberry with CMake
      - name: Configure CMake
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      # 6. Build your project
      - name: Build Project
        run: cmake --build build --parallel

